[package]
name = "codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
prettyplease = "0.2.29"
proc-macro2 = "1.0.93"
quote = "1.0.38"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
strum_macros = "0.27.1"
syn = "2.0.98"
thiserror = "2.0.11"
strum = "0.27.1"
